### ISSUE TITLE
Add callback or chan for failed pushes

### ISSUE THREAD

**Issue by evgeniybaranov** [appleboy/gorush#386]
Hi,

Add the callback or chan with error and token for the failed push notification(apns and fcm). 
For example when you make notification with multiple tokens and some tokens is "BadDeviceToken", I can't handle these requests. PushToIOS or PushToAndroid - return only bool value

**Comment by pennersr** [comment]
There is a sync mode available that should allow for getting error feedback, see: https://github.com/appleboy/gorush/issues/109. Though, I do not fully comprehend the design choice of having to switch to synchronous mode in order to be able to obtain feedback. A few points:

- Receiving and processing error feedback is not really optional. Purging outdated tokens is a requirement for a production ready system.  For example, Apple documents: "By using this information [...] you reduce unnecessary message overhead and improve overall system performance. Query the feedback service daily[...]".

- Given the previous bullet, any production ready system would have to be running in synchronous mode. But, from a push client architecture perspective blocking the client until the push request is fully processed is not desirable. To work around this, clients would have to introduce their own queueing mechanism to work around the risk of getting temporarily blocked.

All in all, a method of obtaining error feedback in asynchronous mode is required. It could be as simple as introducing a new error feedback endpoint that, when queries, returns the feedback collected since the previous call to the endpoint. This way, no complicated callback mechanism would be required.

**Comment by appleboy** [comment]
Maybe I can add the feature to support webhook that receive the notification log if fail.

**Comment by yacir** [comment]
Hi @appleboy i ve pushed a PR if you wana check it.

**Comment by appleboy** [comment]
closed via #414
