### ISSUE TITLE
Getting error while execute gorush  command

### ISSUE THREAD

**Issue by anandhkumar** [appleboy/gorush#410]
I have installed gorush in my linux machine and  executing gorush command, getting following error , I have used v1.9.0 tag

[root@papi_stage gorush]# gorush
-bash: gorush: command not found
[root@papi_stage gorush]# 

go install command successfully executed,
Can you please tell why I am getting this error?

**Comment by vadimkozak** [comment]
try to run using `./gorush `
Thats happens because you have compile from source and as a result you get a single executable file. You can create linux service to run it in production by putting path to binary to service config 

`sudo nano /etc/systemd/system/gorush.service`

`[Unit]
Description= gorush service description
After=network.target
[Service]
User=root
Group=www-data
ExecStart=/home/path/to/binary/gorush
[Install]
WantedBy=multi-user.target`

then execute it as `sudo systemctl start gorush`

**Comment by appleboy** [comment]
@anandhkumar Please move the gorush binary file to `/usr/local/bin/` or any path which in `$PATH` variable.

**Comment by slimus** [comment]
@appleboy close this issue?

**Comment by appleboy** [comment]
@slimus ok, please try the latest version or v1.12.0
